language: scala

scala:
 - 2.11.11

jdk:
 - oraclejdk8

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

script:
  - sbt -no-colors -J-Xss2m ++$TRAVIS_SCALA_VERSION spark_20/test
  - sbt -no-colors -J-Xss2m ++$TRAVIS_SCALA_VERSION spark_21/test
  - sbt -no-colors -J-Xss2m ++$TRAVIS_SCALA_VERSION spark_22/test
