language: scala

scala:
 - 2.11.11

jdk:
 - oraclejdk8

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

script:
  - sbt -DsparkVersion=$SPARK_VERSION -no-colors -J-Xss2m ++$TRAVIS_SCALA_VERSION test

env:
  matrix:
    - SPARK_VERSION=2.0.2
    - SPARK_VERSION=2.1.2
    - SPARK_VERSION=2.2.0